import { QuestionnaireAnswers } from "./types";

export const DEFAULT_ANSWERS: QuestionnaireAnswers = {
  q1: {},
  q2: "",
  q3: [],
  q3_custom: "",
  q4: [],
  q4_custom: "",
  q5: [],
  q6: [],
  q6_custom: "",
  q8: [],
  q8_custom: "",
  q9: "",
  q10: [],
  q11: {},
  q12: [],
  q13: [],
  q14: [],
  q15: [],
  q16: "",
  q17: "",
  q18: "",
  q19: "",
  q20: "",
  q21: "",
  q22: "",
  q23: "",
  q24: [],
  q25: [],
  q26: "",
};

export const BELLE_ANSWERS: Partial<QuestionnaireAnswers> = {
  q1: {
    "Early riser|Night owl": "left",
    "Plan every detail|Figure it out as I go": "left",
    "Big group energy|Deep 1-on-1 conversations": "right",
    "Lead from the front|Empower from behind": "left",
    "Show me the data|Trust your gut": "left",
    "Overdressed|Underdressed": "left",
    "Say more|Say less": "right",
    "Blends in then surprises you|Fills the room immediately": "left",
  },
  q2: "Wake up early without an alarm. Coffee first, something good \u2014 not instant. A long run, usually alone, usually with a podcast on nutrition or business. Back home, cook something proper for breakfast. Then either deep work on Verifood or a slow morning reading. No screens in bed.",
  q3: ["Nutrition & food science", "Building a startup", "Fitness & training", "Health systems"],
  q3_custom: "Grocery retail innovation",
  q4: ["Food & recipes", "Fitness & training", "Founders & startups", "Science & research", "Books & reading"],
  q4_custom: "",
  q5: ["Earthy & warm", "Editorial & polished", "Clean & minimal"],
  q6: ["My work / business", "Behind-the-scenes of building", "Health & fitness", "Industry insights"],
  q6_custom: "Nutrition science explainers",
  q8: ["Jenna Kutcher", "Reshma Saujani", "Marie Forleo", "Brene Brown", "Sara Blakely"],
  q8_custom: "",
  q9: "They\u2019re all builders who lead with substance over style, and none of them sound like they\u2019re performing.",
  q10: [
    "The hustle-porn guru",
    "The wellness fairy",
    "The corporate robot",
    "The humble-brag founder",
    "The always-positive toxic optimist",
  ],
  q11: {
    "Serious|Playful": 35,
    "Polished|Raw & unfiltered": 30,
    "Quiet authority|Loud energy": 25,
    "Warm & emotional|Sharp & analytical": 55,
    "Traditional|Unconventional": 60,
  },
  q12: ["Credible", "Warm", "Ambitious", "Grounded"],
  q13: ["Editorial", "Warm", "Minimal", "Earthy"],
  q14: [0, 4, 8],
  q15: ["Jenna Kutcher", "Reshma Saujani", "Marie Forleo"],
  q16: "Chartered accountant who restructured failing companies \u2014 now building a nutrition startup. The skills transfer more than people expect. I read cap tables and clinical nutrition studies, usually before 7am.",
  q17: "Making sense of complex things. People ask me to break down a problem \u2014 a business model, a nutrition claim, a career decision \u2014 and give them the honest, evidence-based answer, not the comfortable one.",
  q18: "The research doesn\u2019t suggest this helps. It shows it does \u2014 repeatedly, across populations, under rigorous conditions.",
  q19: "Preachy. Like a wellness influencer. Like I\u2019m selling a lifestyle I don\u2019t actually live. Cold or corporate.",
  q20: "Game-changing, passionate about, hustle, authentic journey, leveraging synergies, nourish your body, holistic wellness",
  q21: "Annabelle Body",
  q22: "Founder of Verifood \u2014 building AI-powered personalised nutrition at the point of grocery purchase. B2B2C model via dietitian and grocery retailer partnerships.",
  q23: "BSc Biological Sciences (Exeter) \u00b7 ICAEW Chartered Accountant \u00b7 Strategy consulting at Deloitte UK and AlixPartners \u00b7 HBS MBA Candidate 2026 \u00b7 Competitive Hyrox athlete",
  q24: ["LinkedIn", "Instagram", "Newsletter"],
  q25: ["Follow my build", "Connect on LinkedIn", "Learn about my company"],
  q26: "Graduating HBS May 2026. Need brand locked before then. Actively fundraising pre-seed.",
};
