import { QuestionnaireAnswers } from "./types";

export const DEFAULT_ANSWERS: QuestionnaireAnswers = {
  q1: "",
  q2: "",
  q3: [],
  q4: "",
  q5: "",
  q6: "",
  q7: "",
  q8: "",
  q9: "",
  q10: "",
  q11: [],
  q12: [],
  q13: [],
  q14: [],
  q15: "",
  q16: [],
  q17: "",
  q18: "",
  q19: [],
  q20: "",
  q21: [],
  q22: "",
};

export const BELLE_ANSWERS: Partial<QuestionnaireAnswers> = {
  q1: "Annabelle Body",
  q2: "Founder, Verifood",
  q3: ["Investors", "Potential co-founders", "Industry partners"],
  q4: "Pre-seed / seed stage founder",
  q5: "BSc Biological Sciences (Exeter) · ICAEW Chartered Accountant · Strategy consulting at Deloitte UK and AlixPartners · HBS MBA Candidate 2026",
  q6: "The grocery store is the most underutilised health intervention on the planet. I'm building the infrastructure to change that.",
  q7: "Went from restructuring broken companies to building one from scratch. The skills transfer more than people expect.",
  q8: "Verifood — AI-powered personalised nutrition at the point of grocery purchase. B2B2C model via dietitian and grocery retailer partnerships.",
  q9: "People want to eat better but the grocery store gives them no help. We put a personalised nutrition layer at the point of purchase.",
  q10: "The grocery store is the most underutilised health intervention on the planet.",
  q11: ["Credible", "Warm", "Ambitious", "Grounded"],
  q12: ["Editorial", "Warm", "Minimal", "Earthy"],
  q13: [0, 4, 8],
  q14: ["Jenna Kutcher", "Reshma Saujani", "Marie Forleo"],
  q15: "Direct and evidence-based",
  q16: ["Hustle culture", "Wellness cliche", "Corporate jargon", "Diet culture"],
  q17: "The research doesn't suggest this helps. It shows it does — repeatedly, across populations, under rigorous conditions.",
  q18: "Game-changing, passionate about, hustle, authentic journey, leveraging synergies",
  q19: ["LinkedIn", "Instagram", "Newsletter"],
  q20: "@iambeangirl",
  q21: ["Follow my build", "Connect on LinkedIn", "Learn about Verifood"],
  q22: "Graduating HBS May 2026. Need brand locked before then. Actively fundraising pre-seed.",
};
